name: sm_technology
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  http: ^1.2.2
  fluttertoast: ^8.2.8
  tuple: ^2.0.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  connection_notifier: ^2.0.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  intl: ^0.20.1
  sleek_circular_slider: ^2.0.1
  on_process_button_widget: ^2.0.6
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/weather/

